eventoL/eventoL

bower.json
conf/locale/es/LC_MESSAGES/django.po
eventoL/settings.py
manager/admin.py
manager/forms.py
manager/migrations/0002_comment.py
manager/migrations/0003_talkproposal_level.py
manager/migrations/0004_sede_limit_proposal_date.py
manager/models.py
manager/security.py
manager/templates/base-main.html
manager/templates/form_field.html
manager/templates/homepage.html
manager/templates/index.html
manager/templates/talks/comments.html
manager/templates/talks/detail.html
manager/templates/talks/proposal/votes.html
manager/templates/talks/talks_home.html
manager/templates/talks/to_talk_form.html
manager/templatetags/filters.py
manager/urls.py
manager/views.py
requirements.txt

- closes #33
- closes #2
- closes #12
- Votos a propuestas por colaboradores, instaladores o administradores
- Comentar propuestas por colaboradores, instaladores o administradores
- Vistas para charlas, propuestas, ...
- Controlador de horarios disponibles
- Mejora de permisos para base-main y templates con datos para usuarios según su nivel
- Paso a Django 1.7.7
- Detalles encontrados de versiones anteriores
- Nivel en las propuestas de charlas
- Fecha limite para propuestas
- Traducción casi completa ( #17)
- Uso de contacts en base-main

Votos + Comentarios + Talk + Proposal to talk + fecha limite + extras

---

manager/admin.py
manager/models.py
manager/templates/base-main.html

- Al fin Query Set :+1: (closes #4)
- Nueva funcionalidad ("ver en el sitio")
- Arreglo de autocomplete para attende search

Query Set + "ver en el sitio" + Attende Search con autocomplete

---

manager/admin.py
manager/forms.py
manager/models.py
manager/views.py

Forms con entorno limitado

---

manager/templates/base-main.html
manager/templates/talks/comments.html
manager/templates/talks/detail.html
manager/templates/talks/proposal/votes.html
manager/templates/talks/talks_home.html
manager/templatetags/filters.py

- Cambios para is_staff con verificación de sede (#41)
- Mejor responsive en celulares para las charlas y propuestas

is_sede_staff + responsive

---

manager/admin.py
manager/security.py
manager/views.py

- Fix error superuser/collaborator
- Permisos para /admin a todos los collaborators

Fix error superuser/collaborator + Permisos para /admin a todos los collaborators

---

conf/locale/es/LC_MESSAGES/django.po
manager/initial_data.json
manager/models.py
manager/schedule.py
manager/templates/base-main.html
manager/templates/talks/talks_home.html
manager/views.py

closes #85
closes #89 
closes #94 
closes #93 
closes #82
closes #73

mergeo con cronograma y detalles de error encontrado

---

manager/templates/talks/talks_home.html

Solución para el bug de formularios de confirmación de charlas

---

bower.json
conf/locale/es/LC_MESSAGES/django.po
eventoL/settings.py
manager/api/builder.py
manager/api/rest.py
manager/api/urls.py
manager/api/views.py
manager/forms.py
manager/templates/base-main.html
manager/templates/reports/dashboard.html
manager/templates/talks/talks_home.html
manager/urls.py
manager/views.py
requirements.txt

Api + Reportes

---

.gitignore
manager/forms.py
manager/templates/talks/detail.html
manager/templates/talks/proposal/votes.html
manager/templates/talks/upload_presentation.html
manager/urls.py
manager/views.py

Ver primero el PR #108
Editar charlas y propuestas, closes  #78
Desconfirmar charlas confirmadas, closes #99
Presentaciones, closes #110

Presentaciones y edición de charlas confirmadas

---

manager/api/builder.py
manager/migrations/0012_auto_20150526_1820.py
manager/migrations/0013_auto_20150527_1546.py
manager/models.py
manager/templates/reports/dashboard.html

#115 - Fix error de filtrado por sede

Fix error de filtrado por sede en los reportes

---

manager/templates/form_field.html

Muestro labels en los forms-input

Fixes #159

---

eventoL/settings.py
manager/admin.py
manager/api/rest/builder.py
manager/api/rest/router.py
manager/api/rest/serializers.py
manager/forms.py
manager/models.py
manager/schedule.py
manager/security.py
manager/templates/activities/activities_home.html
manager/templates/activities/schedule.html
manager/templates/base-main.html
manager/tests/api/test_api.py
manager/tests/api/test_api_for_django_models.py
manager/views.py

Close #189 - Error 500 al querer ver un talk detail
Close #190 - Cambios en la api para uso de permisos y reportes
Close #180 - Activities y schedule con cosas generadas desde el admin
Close #180 - Letra del cronograma mas pequeña para actividades de poco tiempo
Close #180 - Links de actividades en el cronograma
Close #180 - Desde el admin se tiene que validar el horarios y aula cuando se modifica una actividad
Close #180 - Lista de actividades con actividades no confirmadas (hechas desde el admin)

Arreglos de bugs, nueva api con permisos y detalles de cronograma

---

manager/templates/activities/schedule.html
manager/urls.py
manager/views.py

Close #193 - Error en links de charlas del cronograma

#193 - Arreglo de error de link de charlas

---

manager/models.py
manager/schedule.py

Close #198 - Schedule calcula mal es espacio a ocupar por una charla
Close #197 - room_available no excluye la charla en si mismo

Solución de bugs de schedule

---

manager/templates/activities/schedule.html

#200 - Agrego safe para pasar de N,n% a N.n% que es lo que maneja css

---

manager/security.py
manager/templates/404.html
manager/templates/500.html
manager/views.py

Uso de objects get

---

manager/views.py

Bug sorteo

---

manager/admin.py
manager/schedule.py
manager/tests/test_tagfilters.py

Fix export and schedule

---

manager/forms.py

Double email entry field 

---

eventol/front/src/components/ItemMap/index.jsx
eventol/front/src/components/SliderItems/index.jsx
eventol/front/src/components/TitleList/index.jsx
eventol/front/src/containers/EventHome/index.jsx
eventol/manager/forms.py
eventol/manager/templates/base-main.html
eventol/manager/templates/event/create.html
eventol/manager/templatetags/filters.py

- Add abstract field in create event form
- Fix items with maps (#313)
- Fix url in email contacts (#255)
- Remove some list in eventslug home page (show only upcoming and finished events)

Eventol 2.0 some fixes

---

eventol/eventol/settings.py
requirements.txt

We need it to make SSL config optional

SSL default to 'prefer' and configurable using environment

---

deploy/docker/README.md

Agrego un par de cositas que tuve que hacer para que ande. Cambios menores.

Quickfix deploy/docker/README

---

eventol/manager/security.py
eventol/manager/views.py

Queda pendiente mostrar las actividades a los reviewers. Voy a agregarlo en el PR donde agregamos esos permisos https://github.com/eventoL/eventoL/pull/402

Fix public activities

---

eventol/manager/templates/base-main.html

Remove collaboration tab in events without collaborators

---

Makefile

- #634 - Fix make collectstatic
- #643 - Fix make migrate
- #642 #633 #637 - Fix make deploy-dev

EventoL v2.3.1 - Fix deploy makefile command

---

eventol/manager/views.py

Delete try-except blocks that do db rollbacks (.delete() of db models on failure) and use transaction.atomic() intead

Replace manual db rollbacks with transaction.atomic()

---

develop.md

Agregado en la documentación de desarrollo un posible error y su solución

Agregado a la documentación gdal dependencia

---

Dockerfile

Se actualiza el sistema operativo  que se usa de base.

changes in dockerfile
